twist_pub_topic: /cmd_vel
remote_control_topic: /remote_control
joint_topic: /dynamic_joint_states
gimbal_follow_set_topic: /gimbal_follow_pid/cmd
gimbal_follow_fdb_topic: /gimbal_follow_pid/pid
x_max_speed: 4.0
y_max_speed: 4.0
rotate_max_speed: 4.0
x_max_accel: 2.0
y_max_accel: 2.0
use_break: false
update_rate: 200.0
yaw_encoder_bias: 1.6280826
motor_yaw_hw_id: gimbal_yaw
