diag_freq: 10.0
diagnose_topic: /diagnostics
node_names:
- /diagnostic_aggregator
- /dr16_receiver
- /socket_can_monitor
- /mecanum_chassis_solver
- /chassis_teleop
- /gimbal_control
- /gimbal_teleop
- /dr16_forwarder
- /shooter_controller
respawn: false
update_rate: 10.0
